export const CHITFUND_ABI = [
  // Constructor
  {
    type: "constructor",
    inputs: [
      { name: "_token", type: "address" },
      { name: "_contributionAmount", type: "uint256" },
      { name: "_memberCount", type: "uint256" },
      { name: "_roundDuration", type: "uint256" },
      { name: "_maxDiscountBps", type: "uint256" },
      { name: "_organizer", type: "address" },
      { name: "_guardian", type: "address" },
    ],
  },
  // ─── Read Functions ────────────────────────────────────────────────
  {
    type: "function",
    name: "state",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "phase",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "roundNumber",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "phaseDeadline",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "token",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "contributionAmount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxMemberCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "roundDuration",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxDiscountBps",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "organizer",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "potBalance",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "guardian",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isMember",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasWon",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isDelinquent",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasContributed",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "dividendBalance",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "memberCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMembers",
    inputs: [],
    outputs: [{ name: "", type: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getGroupInfo",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "state", type: "uint8" },
          { name: "phase", type: "uint8" },
          { name: "roundNumber", type: "uint256" },
          { name: "phaseDeadline", type: "uint256" },
          { name: "contributionAmount", type: "uint256" },
          { name: "memberCount", type: "uint256" },
          { name: "currentMemberCount", type: "uint256" },
          { name: "roundDuration", type: "uint256" },
          { name: "maxDiscountBps", type: "uint256" },
          { name: "potBalance", type: "uint256" },
          { name: "token", type: "address" },
          { name: "organizer", type: "address" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMemberStatus",
    inputs: [{ name: "member", type: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "member", type: "address" },
          { name: "hasContributed", type: "bool" },
          { name: "hasWon", type: "bool" },
          { name: "isDelinquent", type: "bool" },
          { name: "missedRounds", type: "uint256" },
          { name: "dividendBalance", type: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCurrentWinner",
    inputs: [],
    outputs: [
      { name: "winner", type: "address" },
      { name: "discountBps", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRoundHistory",
    inputs: [{ name: "round", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "winner", type: "address" },
          { name: "discountBps", type: "uint256" },
          { name: "payout", type: "uint256" },
          { name: "dividendPerMember", type: "uint256" },
          { name: "totalContributed", type: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  // ─── Write Functions ───────────────────────────────────────────────
  {
    type: "function",
    name: "join",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "ragequit",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "contribute",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "commitBid",
    inputs: [{ name: "commitment", type: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revealBid",
    inputs: [
      { name: "discountBps", type: "uint256" },
      { name: "salt", type: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawDividend",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "advancePhase",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "pause",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "unpause",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "emergencyExit",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  // ─── Events ────────────────────────────────────────────────────────
  {
    type: "event",
    name: "MemberJoined",
    inputs: [
      { name: "member", type: "address", indexed: true },
      { name: "memberIndex", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "GroupActivated",
    inputs: [{ name: "timestamp", type: "uint256", indexed: false }],
  },
  {
    type: "event",
    name: "ContributionMade",
    inputs: [
      { name: "member", type: "address", indexed: true },
      { name: "round", type: "uint256", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "BidCommitted",
    inputs: [
      { name: "member", type: "address", indexed: true },
      { name: "round", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "BidRevealed",
    inputs: [
      { name: "member", type: "address", indexed: true },
      { name: "round", type: "uint256", indexed: false },
      { name: "discountBps", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RoundComplete",
    inputs: [
      { name: "round", type: "uint256", indexed: true },
      { name: "winner", type: "address", indexed: false },
      { name: "payout", type: "uint256", indexed: false },
      { name: "dividend", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "DividendWithdrawn",
    inputs: [
      { name: "member", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "GroupPaused",
    inputs: [{ name: "by", type: "address", indexed: true }],
  },
  {
    type: "event",
    name: "EmergencyExit",
    inputs: [{ name: "totalReturned", type: "uint256", indexed: false }],
  },
  {
    type: "event",
    name: "PhaseAdvanced",
    inputs: [
      { name: "newPhase", type: "uint8", indexed: false },
      { name: "deadline", type: "uint256", indexed: false },
    ],
  },
] as const;
